apiVersion: apps/v1
kind: Deployment
metadata:
  name: utils
  labels:
    app: utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utils
  template:
    metadata:
      labels:
        app: utils
    spec:
      containers:
        - name: utils
          image: myutils
          imagePullPolicy: "Never"
          command: ['sh', '-c', 'sleep infinity']